fn main() {
    for proto in ["common.proto", "workload.proto", "control.proto"] {
        println!("cargo:rerun-if-changed=../../proto/{proto}");
    }
    prost_build::compile_protos(
        &[
            "../../proto/common.proto",
            "../../proto/workload.proto",
            "../../proto/control.proto",
        ],
        &["../../proto/"],
    )
    .expect("Failed to compile proto files");

    generate_paths();
    compile_mo_files();
}

fn compile_mo_files() {
    if std::env::var("CARGO_FEATURE_L10N_DEBUG").is_err() {
        return;
    }

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let po_dir = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("po");
    if !po_dir.exists() {
        return;
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mo_root = std::path::Path::new(&out_dir).join("mo");

    for entry in std::fs::read_dir(&po_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("po") {
            continue;
        }
        let lang = path.file_stem().unwrap().to_str().unwrap();
        let mo_subdir = mo_root.join(lang).join("LC_MESSAGES");
        std::fs::create_dir_all(&mo_subdir).unwrap();

        let mo_path = mo_subdir.join("systema.mo");
        let status = std::process::Command::new("msgfmt")
            .arg(&path)
            .arg("-o")
            .arg(&mo_path)
            .status()
            .expect("msgfmt not found — install gettext tools");
        if !status.success() {
            panic!("msgfmt failed for {:?}", path);
        }
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn generate_paths() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = std::path::Path::new(&out_dir).join("paths.rs");

    let runstatedir = "/run";

    let content = format!(r#"// Generated by build.rs — do not edit.
// Compile-time default paths. Override at runtime via environment variables.

pub const SYSTEMD_LIB_UNIT_DIR: &str = "/usr/lib/systemd/system";
pub const SYSTEMD_FIRST_BOOT_FILE: &str = "/run/systemd/first-boot";
pub const SYSTEMD_MACHINE_ID_FILE: &str = "/etc/machine-id";

pub const IPC_SOCKET_PATH: &str = "/run/systema/allocator.sock";
pub const SYSTEMA_FDPASS_SOCK: &str = "/run/systema/fdpass.sock";
pub const CONTROL_SOCKET_PATH: &str = "{runstatedir}/systema/control.socket";

pub const RUNSTATEDIR: &str = "/run";

pub const NOTIFY_DIR: &str = "{runstatedir}/systema/notify";

pub const SYSTEMA_SHELL_PATH: &str = "/bin/sh";
pub const SYSTEMA_SOCKET_HANDLER_PATH: &str = "/usr/lib/systema/socket-handler";

pub const LOCALE_DIR: &str = "/usr/share/locale";

pub const LOG_DIR: &str = "/var/log/systema";

pub const UNIT_SEARCH_PATHS: &[&str] = &[
    "/etc/systema",
    "/run/systema",
    "/usr/local/lib/systema",
    "/usr/lib/systema",
    "/etc/systemd/system",
    "/usr/lib/systemd/system",
    "/lib/systemd/system",
];

pub const GENERATOR_SEARCH_PATHS: &[&str] = &[
    "/run/systemd/generator",
    "/run/systemd/generator.late",
    "/etc/systemd/system-generators",
    "/usr/local/lib/systemd/system-generators",
    "/usr/lib/systemd/system-generators",
    "/lib/systemd/system-generators",
];

// Search paths for System F finder executables.  The `systema-sysf`
// executable locates format-specific finder binaries (e.g.
// `systema-sysf.systemd`) in these directories.
pub const FINDER_SEARCH_PATHS: &[&str] = &[
    "/etc/systema/finder",
    "/usr/etc/systema/finder",
    "/usr/local/etc/systema/finder",
    "/opt/systema/finder",
];

pub const RELOAD_SOCKET: &str = "/run/systema/sysf.sock";

pub const SYSTEMA_BIN_SEARCH_PATHS: &[&str] = &[
    "/",
    "/bin",
    "/sbin",
    "/lib/systema",
    "/libexec/systema",
    "/usr/bin",
    "/usr/sbin",
    "/usr/lib/systema",
    "/usr/libexec/systema",
    "/usr/local/bin",
    "/usr/local/sbin",
    "/usr/local/lib/systema",
    "/usr/local/libexec/systema",
    "/opt/systema",
];
"#);

    std::fs::write(&dest_path, content).unwrap();
}
