[package]
name = "systema-sysn"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "systema-sysn"
path = "src/main.rs"

[dependencies]
sysa = { path = "../../libsysa" }

tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
prost.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
inotify.workspace = true
libc = "0.2"

[target.'cfg(any(target_os = "freebsd", target_os = "macos", target_os = "openbsd", target_os = "netbsd", target_os = "dragonfly"))'.dependencies]
libc = "0.2"
