[package]
name = "systema-sysa"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "systema-sysa"
path = "src/main.rs"

[dependencies]
sysa = { path = "../../libsysa" }
systema-sysf = { path = "../systema-sysf" }
systema-sysf-systemd = { path = "../systema-sysf/systema-sysf-systemd" }

tokio.workspace = true
tokio-util.workspace = true
prost.workspace = true
bytes.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
async-trait.workspace = true
uuid.workspace = true
once_cell.workspace = true
libc = "0.2"
parking_lot.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
petgraph.workspace = true
configparser.workspace = true
