//! Shared mutable state for System A.
//!
//! `AllocatorState` is the single source of truth for desired unit states,
//! registered workers, and in-flight jobs. It is protected by a `RwLock` and
//! accessed via `AllocatorHandle` (an `Arc<RwLock<AllocatorState>>`).

use std::collections::{HashMap, HashSet};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::Instant;
use tokio::task::AbortHandle;

use parking_lot::RwLock;
use sysa::event_bus::EventBus;
use tokio::sync::mpsc;
use tokio::sync::RwLock as TokioRwLock;
use tracing::info;
use uuid::Uuid;

use systema_sysf::ir::UnitIR;

use crate::unit::types::{SliceSection, SuccessAction, UnitFile, UnitKind};

/// systemd's root slice unit name (`-.slice`).
///
/// Like other special units it is perpetual: it always exists in memory and
/// is always `active`, wrapping every other unit's cgroup at `/`.
pub const ROOT_SLICE_NAME: &str = "-.slice";

/// Snapshot of a unit's runtime state, kept up-to-date via `method.result`
/// responses and `unit.state_update` push events.  Read synchronously by
/// control-port snapshots.
#[derive(Debug, Clone, Default)]
pub struct CachedUnitState {
    pub active_state: String,
    pub sub_state: String,
    pub main_pid: u32,
    /// Invocation ID (UUID v4) of the current activation, as reported by
    /// the owning worker (or generated by System A for units that report
    /// none, e.g. mount units).  Cleared when the unit reaches
    /// `inactive`/`dead`.
    pub invocation_id: String,
    /// Realtime µs since the epoch when the unit last entered `active`
    /// (systemd `ActiveEnterTimestamp`).  Reset when leaving `active`.
    pub active_enter_timestamp: u64,
    /// Realtime µs since the epoch when the unit last entered `inactive`
    /// or `failed` (systemd `InactiveEnterTimestamp`).  Reset on re-entry
    /// into `active`.
    pub inactive_enter_timestamp: u64,
    /// Worker-specific extensions (e.g. `last_exit_code`, `last_error`).
    pub extensions: HashMap<String, String>,
    /// PIDs wrapped by a scope unit (transient `PIDs=` property), reported
    /// by the System E worker.  Empty for non-scope units.
    pub pids: Vec<u32>,
    /// D-Bus unique name of the scope's controller (the client that created
    /// the transient scope via `StartTransientUnit`).  Empty when none.
    pub controller: String,
}

// --------------------------------------------------------------------------
// Desired state enum
// --------------------------------------------------------------------------

/// The state System A wants a unit to be in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DesiredState {
    Active,
    Inactive,
}

// --------------------------------------------------------------------------
// Job tracking
// --------------------------------------------------------------------------

/// The kind of operation a job represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JobKind {
    Start,
    Stop,
    Restart,
    Reload,
    /// A job that performs no operation (systemd `JOB_NOP`): the root
    /// collapsed to `Nop` (e.g. try-restart of an inactive unit) and the
    /// job completes immediately as done.
    Nop,
}

impl JobKind {
    pub fn as_str(&self) -> &str {
        match self {
            JobKind::Start => "start",
            JobKind::Stop => "stop",
            JobKind::Restart => "restart",
            JobKind::Reload => "reload",
            JobKind::Nop => "nop",
        }
    }
}

// --------------------------------------------------------------------------
// Job mode
// --------------------------------------------------------------------------

/// Describes how a job should behave when another job for the same unit
/// already exists, and which dependencies to expand.
///
/// Mirrors systemd's `JobMode` (`src/basic/unit-def.h`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JobMode {
    /// Fail if a conflicting job is already queued.
    Fail,
    /// Fail if the transaction would stop a running unit or change an
    /// existing job (`systemctl --job-mode=lenient`).
    Lenient,
    /// Replace an existing conflicting job (default).
    Replace,
    /// Like [`JobMode::Replace`] and mark the job irreversible.
    ReplaceIrreversibly,
    /// Start the root and stop every other active unit.
    Isolate,
    /// Flush all pending jobs first.
    Flush,
    /// Ignore both requirement and ordering dependencies.
    IgnoreDependencies,
    /// Ignore requirement dependencies.
    IgnoreRequirements,
    /// Add `TRIGGERED_BY` dependencies (stop jobs only).
    Triggering,
    /// A start job becomes a restart for depending units.
    RestartDependencies,
    /// Legacy systema extension (systemd removed `queue` long ago): return
    /// the id of an already-running job of the same kind instead of
    /// replacing it.
    Queue,
}

impl JobMode {
    /// Parse a `--job-mode=` value. Unknown strings return `None` so the
    /// control-port layer can reject them with `InvalidArgs`, like systemd's
    /// `job_mode_from_string()`.
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "fail" => Some(JobMode::Fail),
            "lenient" => Some(JobMode::Lenient),
            "replace" => Some(JobMode::Replace),
            "replace-irreversibly" => Some(JobMode::ReplaceIrreversibly),
            "isolate" => Some(JobMode::Isolate),
            "flush" => Some(JobMode::Flush),
            "ignore-dependencies" => Some(JobMode::IgnoreDependencies),
            "ignore-requirements" => Some(JobMode::IgnoreRequirements),
            "triggering" => Some(JobMode::Triggering),
            "restart-dependencies" => Some(JobMode::RestartDependencies),
            "queue" => Some(JobMode::Queue),
            _ => None,
        }
    }
}

/// The current status of a job.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum JobStatus {
    Running,
    Done,
    Failed(String),
    Cancelled,
}

/// A job tracks an in-flight unit operation.
#[derive(Debug)]
pub struct Job {
    pub id: u64,
    pub unit_name: String,
    pub kind: JobKind,
    pub status: JobStatus,
    /// Handle to abort the job's timeout task when the job completes normally.
    pub timeout_abort: Option<AbortHandle>,
}

/// Notification sent over an internal channel so the control port can emit
/// the `JobRemoved` signal when a job finishes.
#[derive(Debug)]
pub struct JobCompletion {
    pub job_id: u64,
    pub unit_name: String,
    pub result: JobResultKind,
}

/// Notification sent when a new job is created, so the control port can emit
/// the `JobNew` signal.
#[derive(Debug, Clone)]
pub struct JobNewInfo {
    pub job_id: u64,
    pub unit_name: String,
}

/// Tracks start attempts for restart rate-limiting.
#[derive(Debug, Clone)]
pub struct StartLimitState {
    /// Timestamps of recent start attempts (within the interval).
    pub timestamps: Vec<Instant>,
}

impl StartLimitState {
    pub fn new() -> Self {
        StartLimitState {
            timestamps: Vec::new(),
        }
    }

    /// Prune timestamps older than `interval` and check if the burst limit
    /// has been exceeded.
    ///
    /// Mirrors systemd's `ratelimit_configured()`: a zero interval or zero
    /// burst disables rate limiting entirely (`StartLimitIntervalSec=0` or
    /// `StartLimitBurst=0` in systemd mean "no limiting").
    pub fn check_rate_limit(&mut self, interval: std::time::Duration, burst: u32) -> bool {
        if interval.is_zero() || burst == 0 {
            return true;
        }
        let now = Instant::now();
        self.timestamps
            .retain(|t| now.duration_since(*t) < interval);
        if self.timestamps.len() >= burst as usize {
            return false;
        }
        self.timestamps.push(now);
        true
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum JobResultKind {
    Done,
    Failed,
    Cancelled,
    Timeout,
    Dependency,
    Skipped,
}

impl JobResultKind {
    pub fn as_str(&self) -> &str {
        match self {
            JobResultKind::Done => "done",
            JobResultKind::Failed => "failed",
            JobResultKind::Cancelled => "cancelled",
            JobResultKind::Timeout => "timeout",
            JobResultKind::Dependency => "dependency",
            JobResultKind::Skipped => "skipped",
        }
    }
}

// --------------------------------------------------------------------------
// Worker registry
// --------------------------------------------------------------------------

/// A registered System Worker connection.
pub struct WorkerEntry {
    pub worker_id: String,
    /// Unit types this worker handles, e.g. ["service"].
    pub unit_types: Vec<String>,
    /// Whether the worker implements the `unit.define` protocol and may be
    /// asked to synthesize definitions for dynamic units of its types.
    pub supports_unit_define: bool,
    /// Whether the worker declared itself ready (`worker.ready` envelope).
    pub ready: bool,
    /// Channel to send pre-encoded envelopes (method calls, etc.).
    pub envelope_tx: mpsc::Sender<bytes::Bytes>,
}

/// A staging area bound to a single worker UID.
#[derive(Debug, Clone)]
pub struct StagingArea {
    pub name: String,
    pub uid: u32,
    pub units: HashMap<String, UnitIR>,
}

/// Validate a staging area name.
///
/// Allowed characters: upper/lowercase letters, `_`, `/`, `\`, `-`.
/// Maximum length: 64 characters.
pub fn is_valid_staging_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 64
        && name
            .bytes()
            .all(|b| b.is_ascii_alphabetic() || matches!(b, b'_' | b'/' | b'\\' | b'-'))
}

// --------------------------------------------------------------------------
// Allocator state
// --------------------------------------------------------------------------

pub struct AllocatorState {
    /// All loaded unit files.
    pub units: HashMap<String, UnitFile>,
    /// Alias names → canonical unit names (e.g. `display-manager.service` →
    /// `lightdm.service`).  Populated on every commit from the units' declared
    /// aliases; all job dispatch and unit lookups resolve through this map so
    /// an alias is never treated as a separate unit.
    pub aliases: HashMap<String, String>,
    /// Desired state for each named unit.
    pub desired: HashMap<String, DesiredState>,
    /// In-flight jobs keyed by job ID.
    pub jobs: HashMap<u64, Job>,
    /// Registered workers keyed by worker_id.
    pub workers: HashMap<String, WorkerEntry>,
    /// Maps task_id (IPC level) → JobKind so we can correctly update state
    /// when a method.result arrives.
    pub task_kinds: HashMap<u64, JobKind>,
    /// Channel to push job-completion events to the in-process event bus so
    /// control-port sessions relay `JobRemoved` signals to System Wrapper.
    pub job_completion_tx: Option<tokio::sync::mpsc::UnboundedSender<JobCompletion>>,
    /// Channel to push unit-loaded events to the in-process event bus so
    /// control-port sessions relay `unit.new` snapshots to System Wrapper.
    pub unit_loaded_tx: Option<tokio::sync::mpsc::UnboundedSender<String>>,
    /// Channel to push job-creation events to the in-process event bus so
    /// control-port sessions relay `JobNew` signals to System Wrapper.
    pub job_new_tx: Option<tokio::sync::mpsc::UnboundedSender<JobNewInfo>>,
    /// Completion senders for serial task execution — keyed by task_id.
    /// When a task completes, `handle_task_result` sends `()` through the
    /// corresponding channel so the next task in the serial chain proceeds.
    pub serial_completion_txs: HashMap<u64, tokio::sync::oneshot::Sender<()>>,
    /// Completion senders for pending `unit.define` requests — keyed by the
    /// request_id of the envelope sent to the worker.  The IPC receiver
    /// completes the channel when the worker's `unit.define_result` arrives.
    pub unit_define_txs: HashMap<u64, tokio::sync::oneshot::Sender<sysa::proto::UnitDefineResult>>,
    /// Restart rate-limiting state, keyed by unit name.
    pub start_limit_state: HashMap<String, StartLimitState>,
    /// In-process event bus for pub/sub event distribution.
    /// Wrapped in `Arc<TokioRwLock>` so it can be accessed across `.await` points
    /// inside `tokio::spawn`-ed tasks (parking_lot guards are not `Send`).
    pub event_bus: Arc<TokioRwLock<EventBus>>,

    /// Staging areas for unit registration, keyed by the (uid, name) pair.
    ///
    /// Each entry is the minimal unit of identity: a worker UID may own
    /// several staging areas distinguished by name, and every UID can access
    /// all areas it owns (regardless of name).  Areas are created by
    /// `RegisterUnits`, queried by `StagingQuery`, committed by `CommitUnits`
    /// (which removes the area), and are inaccessible to callers whose UID
    /// does not match the area's owner.
    pub staging_areas: HashMap<(u32, String), StagingArea>,

    /// Reference counts between units — maps target unit name to the set of
    /// source unit names that hold a reference to it.
    ///
    /// When unit A has Requires=/Wants=/BindsTo=unit-B, A is said to "ref" B.
    /// A unit with zero references is a candidate for unloading.
    pub ref_counts: HashMap<String, HashSet<String>>,

    /// External control-port client reference counts (RefUnit/UnrefUnit).
    /// Maps unit_name → ref_count. Prevents unit from being unloaded while >0.
    pub n_refs: HashMap<String, u64>,

    /// Maps unit_name → current invocation_id (UUID v4).
    /// Set when a Start/Restart task is dispatched, cleared on Stop/Failure.
    /// Used by GetUnitByInvocationID.
    pub invocation_ids: HashMap<String, String>,

    /// Runtime state cache populated from `method.result` IPC responses
    /// and `unit.state_update` push events.
    /// Control-port snapshots read from this cache synchronously.
    pub unit_states: HashMap<String, CachedUnitState>,

    /// Unit ownership table: unit_name → worker_id.
    ///
    /// An owner is assigned when a job for the unit is dispatched to a
    /// worker (and implicitly when a `.automount` unit is started, since its
    /// companion `.mount` unit is managed by the same worker).  Ownership is
    /// cleared when the unit's reported state becomes `inactive`/`dead`.
    /// Incremental `unit.state_update` pushes are only accepted from the
    /// current owner; unknown or unowned units are ignored with a warning.
    pub unit_owners: HashMap<String, String>,

    /// Cgroup runtime metrics cache, populated from `cgroup.metrics` pushes
    /// from System R.  Values are opaque name-keyed numbers; System A never
    /// interprets them, it only relays them to the systemd-compatible
    /// control-port properties.  Not subject to the unit ownership table
    /// (informational).
    pub cgroup_metrics: HashMap<String, sysa::proto::UnitCgroupMetrics>,

    /// Active login sessions per UID, keyed by the session scope's unit
    /// name (systemd-logind semantics).  A session appears when its
    /// `session-<id>.scope` becomes active (scopes whose `Slice=` is a
    /// `user-<UID>.slice`) and disappears when the scope dies.  The per-UID
    /// count is forwarded to System R (`user.sessions`) on every change so
    /// the user's `user-<UID>.slice` follows its sessions.
    pub user_sessions: HashMap<u32, HashSet<String>>,

    /// Channel to the [`ReloadTask`](crate::reload_task) for enqueuing
    /// reload requests.  Set by `main` after spawning the task; `None`
    /// before initialisation.
    pub reload_tx: Option<tokio::sync::mpsc::Sender<crate::reload_task::ReloadRequest>>,
}

impl AllocatorState {
    pub fn new() -> Self {
        let mut state = AllocatorState {
            units: HashMap::new(),
            aliases: HashMap::new(),
            desired: HashMap::new(),
            jobs: HashMap::new(),
            workers: HashMap::new(),
            task_kinds: HashMap::new(),
            job_completion_tx: None,
            unit_loaded_tx: None,
            job_new_tx: None,
            serial_completion_txs: HashMap::new(),
            unit_define_txs: HashMap::new(),
            start_limit_state: HashMap::new(),
            event_bus: Arc::new(TokioRwLock::new(EventBus::new())),
            staging_areas: HashMap::new(),
            ref_counts: HashMap::new(),
            n_refs: HashMap::new(),
            invocation_ids: HashMap::new(),
            unit_states: HashMap::new(),
            unit_owners: HashMap::new(),
            cgroup_metrics: HashMap::new(),
            user_sessions: HashMap::new(),
            reload_tx: None,
        };
        state.ensure_root_slice();
        state
    }

    /// Synthesise systemd's implicit root slice (`-.slice`).
    ///
    /// systemd keeps `-.slice` as a perpetual special unit that is always
    /// loaded and always `active` (`unit_load`/`unit_start` never touch it).
    /// The allocator mirrors that by creating it up front and marking it
    /// active so that control-port lookups, per-unit objects, and the
    /// System R active-unit replay all see it — without it, `systemctl
    /// status` fails on the missing `_2d_2eslice` object and the overview's
    /// cgroup tree is empty.
    fn ensure_root_slice(&mut self) {
        if self.units.contains_key(ROOT_SLICE_NAME) {
            return;
        }
        let mut unit = UnitFile::new(ROOT_SLICE_NAME);
        unit.unit.description = sysa::l10n::t_("Root Slice").to_string();
        unit.slice = Some(SliceSection::default());
        self.units.insert(ROOT_SLICE_NAME.to_string(), unit);

        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_micros() as u64)
            .unwrap_or(0);
        self.unit_states.insert(
            ROOT_SLICE_NAME.to_string(),
            CachedUnitState {
                active_state: "active".to_string(),
                sub_state: "active".to_string(),
                main_pid: 0,
                invocation_id: generate_invocation_id(),
                active_enter_timestamp: now,
                inactive_enter_timestamp: 0,
                extensions: HashMap::new(),
                pids: Vec::new(),
                controller: String::new(),
            },
        );
        self.desired
            .insert(ROOT_SLICE_NAME.to_string(), DesiredState::Active);
    }

    /// Commit the staging area identified by the (uid, name) pair into the
    /// active unit set.
    ///
    /// The commit is atomic:
    ///
    /// - Every `UnitIR` is validated (new units require `unit_type`) before
    ///   anything is mutated; a validation failure aborts the commit, leaves
    ///   `self.units` untouched, and preserves the staging area so the worker
    ///   can still query or retry it.
    /// - Existing units are *merged* (only the entries provided in the IR are
    ///   overwritten — e.g. a mount-table commit carrying only `[Mount]`
    ///   config never clobbers the unit's `description`); new units are
    ///   created from the IR.
    ///
    /// The staging area is removed only after a fully successful merge.
    pub fn commit_staging(&mut self, uid: u32, name: &str) -> Result<u32, String> {
        let Some(area) = self.staging_areas.get(&(uid, name.to_string())) else {
            // Idempotent by design: a successful commit consumes the staging
            // area, and finders drive register → commit cycles under a fixed
            // per-finder staging name (System R additionally runs them from
            // concurrent tasks).  When two cycles overlap, the first commit
            // publishes — and removes — the shared area, so a sibling commit
            // legitimately finds it already consumed.  Treat that as a repeat
            // of an already-satisfied commit, not an error.
            info!(
                "commit_staging(UID={uid}, name={name}): staging area already consumed \
                 (idempotent commit)"
            );
            return Ok(0);
        };

        let unit_count = area.units.len() as u32;
        info!("commit_staging(UID={uid}, name={name}): merging {unit_count} units");

        let (created, updated) = {
            let units: HashMap<String, UnitIR> = area.units.clone();
            self.merge_units(&units)?
        };

        // Phase 3 (finalize): consume the staging area.
        self.staging_areas.remove(&(uid, name.to_string()));
        if created > 0 {
            info!("commit_staging(UID={uid}, name={name}): created {created} new unit(s)");
        }
        if updated > 0 {
            info!("commit_staging(UID={uid}, name={name}): updated {updated} existing unit(s)");
        }

        Ok(unit_count)
    }

    /// Merge a set of [`UnitIR`] definitions into the active unit set.
    ///
    /// This is the shared core of `commit_staging()` (the finder path used
    /// by System D / System R / System F) and the `unit.define` on-demand
    /// materialization path: the same idempotent merge-over-existing
    /// semantics apply to both.
    ///
    /// The merge is atomic:
    ///
    /// - Every `UnitIR` is validated (new units require `unit_type`) before
    ///   anything is mutated; a validation failure aborts the merge and
    ///   leaves `self.units` untouched.
    /// - Existing units are *merged* (only the entries provided in the IR are
    ///   overwritten); new units are created from the IR.
    ///
    /// Returns the number of created and updated units.
    pub fn merge_units(
        &mut self,
        units: &HashMap<String, UnitIR>,
    ) -> Result<(usize, usize), String> {
        // Phase 1 (plan): build every new UnitFile up front so a missing
        // required field aborts the commit before anything is mutated.
        let mut new_units: Vec<(String, UnitFile)> = Vec::with_capacity(units.len());
        for ir in units.values() {
            if !self.units.contains_key(&ir.id) {
                new_units.push(unit_file_from_ir(ir)?);
            }
        }

        // Phase 2 (apply): patch existing units and insert new ones.  All
        // steps are infallible, so a failure cannot happen mid-way.
        let mut created = 0usize;
        let mut updated = 0usize;
        for ir in units.values() {
            if let Some(existing) = self.units.get_mut(&ir.id) {
                apply_ir_patch(ir, existing);
                updated += 1;
            }
        }
        for (unit_name, unit) in new_units {
            self.units.insert(unit_name.clone(), unit);
            created += 1;
            // Notify the event bus so a unit.new is pushed to control-plane
            // consumers (bridge flavors); the merge funnel covers finder
            // commits (System F/D/R) and unit.define.
            if let Some(ref tx) = self.unit_loaded_tx {
                let _ = tx.send(unit_name);
            }
        }

        self.rebuild_alias_map();
        self.rebuild_ref_counts();

        Ok((created, updated))
    }

    /// Return the canonical name of `name`, resolving aliases to their target
    /// unit (identity for non-alias names).
    pub fn resolve_unit_name(&self, name: &str) -> String {
        self.aliases
            .get(name)
            .cloned()
            .unwrap_or_else(|| name.to_string())
    }

    /// Create a staging area for a given UID, or merge into an existing one.
    ///
    /// Re-registering under an already-existing (uid, name) pair reuses that
    /// area, git-index style: units whose name already exists are overwritten
    /// by the incoming ones, and new units are added (the union of both).
    /// Returns the total number of units staged after the merge.
    ///
    /// Returns an error only if `name` does not conform to the staging area
    /// naming rules.
    pub fn init_staging_area(
        &mut self,
        uid: u32,
        name: &str,
        units: HashMap<String, UnitIR>,
    ) -> Result<u32, String> {
        if !is_valid_staging_name(name) {
            return Err(sysa::l10n::fmt(
                sysa::l10n::t_(
                    "invalid staging area name '{name}': must be at most 64 characters long \
                 and contain only letters, underscores, slashes, backslashes, or hyphens",
                ),
                &[("name", &name.to_string())],
            ));
        }
        let count = {
            let area = self
                .staging_areas
                .entry((uid, name.to_string()))
                .or_insert_with(|| StagingArea {
                    name: name.to_string(),
                    uid,
                    units: HashMap::new(),
                });
            for (id, ir) in units {
                area.units.insert(id, ir);
            }
            area.units.len() as u32
        };
        info!("init_staging_area(UID={uid}, name={name}): {count} units");
        Ok(count)
    }

    /// Return the staging area identified by the (uid, name) pair.
    pub fn get_staging_area(&self, uid: u32, name: &str) -> Option<&StagingArea> {
        self.staging_areas.get(&(uid, name.to_string()))
    }

    /// Find every staging area owned by the given UID.
    pub fn get_staging_areas_by_uid(&self, uid: u32) -> Vec<&StagingArea> {
        self.staging_areas
            .iter()
            .filter(|((owner, _), _)| *owner == uid)
            .map(|(_, a)| a)
            .collect()
    }

    /// Find staging areas whose name matches (across all UIDs).
    pub fn get_staging_areas_by_name(&self, name: &str) -> Vec<&StagingArea> {
        self.staging_areas
            .values()
            .filter(|a| a.name == name)
            .collect()
    }

    /// List every staging area as (uid, name) pairs (no units).
    pub fn list_staging_areas(&self) -> Vec<(u32, String)> {
        self.staging_areas
            .iter()
            .map(|((uid, name), _)| (*uid, name.clone()))
            .collect()
    }

    /// Return all staging areas (full data).
    pub fn all_staging_areas(&self) -> &HashMap<(u32, String), StagingArea> {
        &self.staging_areas
    }

    /// Record that `source` holds a reference to `target`.
    ///
    /// This is used to track unit dependency relationships:
    /// when unit A requires/wants/binds-to unit B, A refs B.
    /// A unit with zero refs is a candidate for unloading.
    pub fn ref_unit(&mut self, source: &str, target: &str) {
        if source == target {
            return;
        }
        self.ref_counts
            .entry(target.to_string())
            .or_default()
            .insert(source.to_string());
    }

    /// Return the set of unit names that reference `target`.
    pub fn get_refs(&self, target: &str) -> Vec<String> {
        self.ref_counts
            .get(target)
            .map(|sources| sources.iter().cloned().collect())
            .unwrap_or_default()
    }

    /// Rebuild the alias table from every loaded unit's declared aliases and
    /// rewrite all unit-to-unit references to canonical names.
    ///
    /// systemd treats an alias (e.g. `display-manager.service` for
    /// `lightdm.service`, declared via `[Install] Alias=` or a unit-file
    /// symlink) as another name for the same unit.  Without alias resolution,
    /// the same program would be started once per name, racing for the same
    /// resources.  After every commit we therefore (1) record which names are
    /// aliases of which canonical unit and (2) rewrite every dependency,
    /// ordering, and install reference so the scheduler and the reference
    /// graph only ever deal with canonical names.
    pub(crate) fn rebuild_alias_map(&mut self) {
        self.aliases.clear();
        // Collect declared aliases first to avoid borrow conflicts.
        let mut declared: Vec<(String, String)> = Vec::new();
        for (name, unit) in &self.units {
            for alias in &unit.install.alias {
                declared.push((alias.clone(), name.clone()));
            }
        }
        for (alias, canonical) in declared {
            // A real unit's name is not an alias — the real unit wins.
            if alias == canonical || self.units.contains_key(&alias) {
                continue;
            }
            self.aliases.entry(alias).or_insert(canonical);
        }
        // Rewrite every reference from an alias to its canonical name.
        for unit in self.units.values_mut() {
            rewrite_alias_refs(&mut unit.unit.after, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.before, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.requires, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.wants, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.conflicts, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.binds_to, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.requisite, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.part_of, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.upholds, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.on_success, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.on_failure, &self.aliases);
            rewrite_alias_refs(&mut unit.unit.propagates_reload_to, &self.aliases);
            rewrite_alias_refs(&mut unit.install.wanted_by, &self.aliases);
            rewrite_alias_refs(&mut unit.install.required_by, &self.aliases);
            rewrite_alias_refs(&mut unit.install.also, &self.aliases);
            if let Some(timer) = &mut unit.timer {
                if !timer.unit.is_empty() {
                    if let Some(canonical) = self.aliases.get(&timer.unit) {
                        timer.unit = canonical.clone();
                    }
                }
            }
            if let Some(path) = &mut unit.path {
                if !path.unit.is_empty() {
                    if let Some(canonical) = self.aliases.get(&path.unit) {
                        path.unit = canonical.clone();
                    }
                }
            }
        }
    }

    /// Rebuild reference counts from the current unit set.
    ///
    /// Scans every loaded unit's dependency declarations and populates
    /// `ref_counts` accordingly.  Call this after `commit_staging()` or
    /// `set_staging_units()`.
    pub fn rebuild_ref_counts(&mut self) {
        self.ref_counts.clear();
        // Collect all (source, dep) pairs first to avoid borrow conflicts.
        let mut deps: Vec<(String, String)> = Vec::new();
        for (src, unit) in &self.units {
            for dep in unit.unit.requires.iter() {
                deps.push((src.clone(), dep.clone()));
            }
            for dep in unit.unit.wants.iter() {
                deps.push((src.clone(), dep.clone()));
            }
            for dep in unit.unit.binds_to.iter() {
                deps.push((src.clone(), dep.clone()));
            }
            for dep in unit.unit.requisite.iter() {
                deps.push((src.clone(), dep.clone()));
            }
            for dep in unit.unit.upholds.iter() {
                deps.push((src.clone(), dep.clone()));
            }
            for dep in unit.unit.part_of.iter() {
                deps.push((src.clone(), dep.clone()));
            }
        }
        for (src, dep) in &deps {
            self.ref_unit(src, dep);
        }
    }
}

/// Replace every name in `names` that is an alias with its canonical name.
fn rewrite_alias_refs(names: &mut HashSet<String>, aliases: &HashMap<String, String>) {
    if names.is_empty() || aliases.is_empty() {
        return;
    }
    let mut rewritten = HashSet::new();
    for name in names.drain() {
        rewritten.insert(
            aliases
                .get(&name)
                .cloned()
                .unwrap_or_else(|| name.to_string()),
        );
    }
    *names = rewritten;
}

/// Apply a partial [`UnitIR`] update onto an existing [`UnitFile`].
///
/// Only entries actually provided by the IR (`Some` fields) are overwritten;
/// everything else keeps its current value.  This is the merge semantics of
/// `commit_staging` for units that already exist in the runtime cache.
fn apply_ir_patch(ir: &UnitIR, uf: &mut UnitFile) {
    if let Some(kind) = &ir.unit_type {
        uf.kind = unit_kind_from_type(kind);
    }
    if let Some(description) = &ir.description {
        uf.unit.description.clone_from(description);
    }
    if let Some(slice) = &ir.slice {
        uf.unit.slice.clone_from(slice);
    }

    // Map dependency fields when the whole dependency set is provided.
    if let Some(deps) = &ir.dependencies {
        uf.unit.after.clone_from(&deps.after);
        uf.unit.before.clone_from(&deps.before);
        uf.unit.requires.clone_from(&deps.requires);
        uf.unit.wants.clone_from(&deps.wants);
        uf.unit.conflicts.clone_from(&deps.conflicts);
        uf.unit.binds_to.clone_from(&deps.binds_to);
        uf.unit.requisite.clone_from(&deps.requisite);
        uf.unit.part_of.clone_from(&deps.part_of);
        uf.unit.upholds.clone_from(&deps.upholds);
        uf.unit.on_success.clone_from(&deps.on_success);
        uf.unit.on_failure.clone_from(&deps.on_failure);
        uf.unit
            .propagates_reload_to
            .clone_from(&deps.propagates_reload_to);
        uf.unit.success_action = SuccessAction::from(deps.success_action.as_str());
        uf.unit.default_dependencies = deps.default_dependencies;
    }

    if let Some(wanted) = &ir.wanted_by {
        uf.install.wanted_by = wanted.iter().cloned().collect();
    }
    if let Some(required) = &ir.required_by {
        uf.install.required_by = required.iter().cloned().collect();
    }
    if !ir.aliases.is_empty() {
        uf.install.alias.clear();
        uf.install.alias.extend(ir.aliases.iter().cloned());
    }

    // Copy section configs when provided.
    if let Some(svc) = &ir.service {
        uf.service = Some(service_config_to_section(svc));
    }
    if let Some(mnt) = &ir.mount {
        uf.mount = Some(mount_config_to_section(mnt));
    }
    if let Some(amt) = &ir.automount {
        uf.automount = Some(automount_config_to_section(amt));
    }
    if let Some(tmr) = &ir.timer {
        uf.timer = Some(timer_config_to_section(tmr));
    }
    if let Some(sock) = &ir.socket {
        uf.socket = Some(socket_config_to_section(sock));
    }

    // Resource-control directives apply to whichever cgroup-owned section the
    // unit's kind owns (`[Service]`, `[Slice]`, or `[Scope]`).
    if let Some(rc) = &ir.resource_control {
        let section_rc = resource_control_to_section(rc);
        match uf.kind {
            UnitKind::Service => {
                uf.service.get_or_insert_with(Default::default).rc = section_rc;
            }
            UnitKind::Slice => {
                uf.slice.get_or_insert_with(Default::default).rc = section_rc;
            }
            UnitKind::Scope => {
                uf.scope.get_or_insert_with(Default::default).rc = section_rc;
            }
            _ => {}
        }
    }
}

/// Convert a [`UnitIR`] into a brand-new internal [`UnitFile`] for units
/// that do not exist in the runtime cache yet.
///
/// This is the reverse of the conversion in `systema-sysf-systemd`'s finder.
/// Because every IR entry except `id` is optional, creating a unit requires
/// `unit_type` to be present; a missing required field is reported as an
/// error so the worker that submitted the IR receives the failure.
fn unit_file_from_ir(ir: &UnitIR) -> Result<(String, UnitFile), String> {
    let unit_type = ir.unit_type.as_ref().ok_or_else(|| {
        sysa::l10n::fmt(
            sysa::l10n::t_("cannot create new unit \"{id}\": missing required field \"unit_type\""),
            &[("id", &(ir.id).to_string())],
        )
    })?;
    let mut uf = UnitFile::new(&ir.id);
    uf.kind = unit_kind_from_type(unit_type);
    // systemd defaults for units that don't specify StartLimit* explicitly.
    uf.unit.start_limit_interval_sec = 10;
    uf.unit.start_limit_burst = 5;
    apply_ir_patch(ir, &mut uf);
    Ok((uf.name.clone(), uf))
}

fn unit_kind_from_type(ty: &systema_sysf::ir::UnitType) -> UnitKind {
    use systema_sysf::ir::UnitType;
    match ty {
        UnitType::Service => UnitKind::Service,
        UnitType::Target => UnitKind::Target,
        UnitType::Mount => UnitKind::Mount,
        UnitType::Automount => UnitKind::Automount,
        UnitType::Timer => UnitKind::Timer,
        UnitType::Socket => UnitKind::Socket,
        UnitType::Slice => UnitKind::Slice,
        UnitType::Scope => UnitKind::Scope,
        UnitType::Swap => UnitKind::Swap,
        UnitType::Path => UnitKind::Path,
        UnitType::Device => UnitKind::Device,
        UnitType::Power => UnitKind::Power,
        UnitType::Other(s) => UnitKind::Unknown(s.clone()),
    }
}

fn service_config_to_section(
    cfg: &systema_sysf::ir::ServiceConfig,
) -> crate::unit::types::ServiceSection {
    use crate::unit::types::ServiceType;
    let svc_type = match cfg.exec_start.first() {
        Some(_) => ServiceType::Simple,
        None => ServiceType::Oneshot,
    };
    crate::unit::types::ServiceSection {
        service_type: svc_type,
        exec_start: cfg.exec_start.iter().map(exec_cmd_from_ir).collect(),
        exec_stop: cfg.exec_stop.iter().map(exec_cmd_from_ir).collect(),
        exec_reload: cfg.exec_reload.iter().map(exec_cmd_from_ir).collect(),
        exec_start_pre: cfg.exec_start_pre.iter().map(exec_cmd_from_ir).collect(),
        exec_start_post: cfg.exec_start_post.iter().map(exec_cmd_from_ir).collect(),
        exec_stop_post: cfg.exec_stop_post.iter().map(exec_cmd_from_ir).collect(),
        working_directory: cfg.working_directory.clone(),
        user: cfg.user.clone(),
        group: cfg.group.clone(),
        pam_name: cfg.pam_name.clone(),
        environment: cfg.environment.clone(),
        environment_file: cfg.environment_file.clone(),
        restart: restart_policy_from_ir(&cfg.restart_policy),
        restart_sec: cfg.restart_sec,
        timeout_start_sec: cfg.timeout_start_sec,
        timeout_stop_sec: cfg.timeout_stop_sec,
        remain_after_exit: cfg.remain_after_exit,
        watchdog_sec: cfg.watchdog_sec,
        kill_signal: cfg.kill_signal.clone(),
        kill_mode: cfg.kill_mode.clone(),
        standard_input: cfg.standard_input.clone(),
        standard_output: cfg.standard_output.clone(),
        standard_error: cfg.standard_error.clone(),
        tty_path: cfg.tty_path.clone(),
        ..Default::default()
    }
}

fn resource_control_to_section(
    rc: &systema_sysf::ir::ResourceControl,
) -> crate::unit::types::ResourceControl {
    crate::unit::types::ResourceControl {
        cpu_quota: rc.cpu_quota.clone(),
        cpu_quota_period: rc.cpu_quota_period.clone(),
        cpu_weight: rc.cpu_weight,
        startup_cpu_weight: rc.startup_cpu_weight,
        cpu_set_cpus: rc.cpu_set_cpus.clone(),
        cpu_set_memory_nodes: rc.cpu_set_memory_nodes.clone(),
        memory_min: rc.memory_min.clone(),
        memory_low: rc.memory_low.clone(),
        memory_high: rc.memory_high.clone(),
        memory_max: rc.memory_max.clone(),
        memory_swap_max: rc.memory_swap_max.clone(),
        io_weight: rc.io_weight,
        startup_io_weight: rc.startup_io_weight,
        io_device_weight: rc.io_device_weight.clone(),
        io_read_bandwidth_max: rc.io_read_bandwidth_max.clone(),
        io_write_bandwidth_max: rc.io_write_bandwidth_max.clone(),
        tasks_max: rc.tasks_max,
        allowed_cpus: rc.allowed_cpus.clone(),
        allowed_memory_nodes: rc.allowed_memory_nodes.clone(),
    }
}

fn exec_cmd_from_ir(cmd: &systema_sysf::ir::ExecCommand) -> crate::unit::types::ExecCommand {
    crate::unit::types::ExecCommand {
        raw: cmd.raw.clone(),
        program: cmd.program.clone(),
        args: cmd.args.clone(),
        ignore_failure: cmd.ignore_failure,
        privileged: cmd.privileged,
        no_env_lookup: false,
        no_kill_on_stop: false,
        no_new_privileges: false,
    }
}

fn restart_policy_from_ir(
    policy: &systema_sysf::ir::RestartPolicy,
) -> crate::unit::types::RestartPolicy {
    use crate::unit::types::RestartPolicy as SdRp;
    match policy {
        systema_sysf::ir::RestartPolicy::No => SdRp::No,
        systema_sysf::ir::RestartPolicy::OnSuccess => SdRp::OnSuccess,
        systema_sysf::ir::RestartPolicy::OnFailure => SdRp::OnFailure,
        systema_sysf::ir::RestartPolicy::OnAbnormal => SdRp::OnAbnormal,
        systema_sysf::ir::RestartPolicy::OnWatchdog => SdRp::OnWatchdog,
        systema_sysf::ir::RestartPolicy::OnAbort => SdRp::OnAbort,
        systema_sysf::ir::RestartPolicy::Always => SdRp::Always,
    }
}

fn mount_config_to_section(
    cfg: &systema_sysf::ir::MountConfig,
) -> crate::unit::types::MountSection {
    crate::unit::types::MountSection {
        what: cfg.what.clone(),
        where_: cfg.where_.clone(),
        type_: cfg.type_.clone(),
        options: cfg.options.clone(),
        timeout_sec: cfg.timeout_sec,
        ..Default::default()
    }
}

// --------------------------------------------------------------------------
// Login-session accounting
// --------------------------------------------------------------------------

/// Update the login-session accounting for one unit state report.
///
/// Only `*.scope` units whose `Slice=` is a `user-<UID>.slice` count as
/// login sessions (systemd-logind semantics): `active` adds the scope to
/// the UID's session set, anything else removes it.  Returns
/// `Some((uid, count))` when the UID's session count *changed*, so the
/// caller can forward the new absolute count to System R; `None` when the
/// unit is not a user session or the count is unchanged.
pub fn track_session(
    sessions: &mut HashMap<u32, HashSet<String>>,
    unit_name: &str,
    slice: &str,
    active: bool,
) -> Option<(u32, usize)> {
    if !unit_name.ends_with(".scope") {
        return None;
    }
    let uid = sysa::unit_name::parse_user_slice_uid(slice)?;
    let set = sessions.entry(uid).or_default();
    let before = set.len();
    if active {
        set.insert(unit_name.to_string());
    } else {
        set.remove(unit_name);
    }
    let after = set.len();
    if set.is_empty() {
        sessions.remove(&uid);
    }
    (before != after).then_some((uid, after))
}

fn automount_config_to_section(
    cfg: &systema_sysf::ir::AutomountConfig,
) -> crate::unit::types::AutomountSection {
    crate::unit::types::AutomountSection {
        where_: cfg.where_.clone(),
        extra_options: cfg.extra_options.clone(),
        timeout_idle_sec: cfg.timeout_idle_sec,
        directory_mode: cfg.directory_mode.clone(),
    }
}

fn timer_config_to_section(
    cfg: &systema_sysf::ir::TimerConfig,
) -> crate::unit::types::TimerSection {
    crate::unit::types::TimerSection {
        on_active_sec: cfg.on_active_sec,
        on_boot_sec: cfg.on_boot_sec,
        on_startup_sec: cfg.on_startup_sec,
        on_unit_active_sec: cfg.on_unit_active_sec,
        on_unit_inactive_sec: cfg.on_unit_inactive_sec,
        on_calendar: cfg.on_calendar.clone(),
        accuracy_sec: cfg.accuracy_sec,
        randomized_delay_sec: cfg.randomized_delay_sec,
        unit: cfg.unit.clone(),
        persistent: cfg.persistent,
        ..Default::default()
    }
}

fn socket_config_to_section(
    cfg: &systema_sysf::ir::SocketConfig,
) -> crate::unit::types::SocketSection {
    crate::unit::types::SocketSection {
        listen_stream: cfg.listen_stream.clone(),
        listen_datagram: cfg.listen_datagram.clone(),
        listen_fifo: cfg.listen_fifo.clone(),
        listen_netlink: cfg.listen_netlink.clone(),
        accept: cfg.accept,
        service: cfg.service.clone(),
        socket_mode: cfg.socket_mode.clone(),
        socket_user: cfg.socket_user.clone(),
        socket_group: cfg.socket_group.clone(),
        backlog: cfg.backlog,
        directory_mode: cfg.directory_mode.clone(),
        ..Default::default()
    }
}

// --------------------------------------------------------------------------
// Handle type
// --------------------------------------------------------------------------

pub type AllocatorHandle = Arc<RwLock<AllocatorState>>;

/// Wraps `Arc<RwLock<AllocatorState>>` with a convenience constructor.
pub struct Allocator;

impl Allocator {
    /// Create a shared handle to a fresh allocator state.
    pub fn handle() -> AllocatorHandle {
        Arc::new(RwLock::new(AllocatorState::new()))
    }
}

// --------------------------------------------------------------------------
// Monotonic ID generator
// --------------------------------------------------------------------------

static NEXT_JOB_ID: AtomicU64 = AtomicU64::new(1);
static NEXT_TASK_ID: AtomicU64 = AtomicU64::new(1);
static NEXT_REQUEST_ID: AtomicU64 = AtomicU64::new(1);

pub fn next_job_id() -> u64 {
    loop {
        let current = NEXT_JOB_ID.load(Ordering::Relaxed);
        let next = current.wrapping_add(1);
        if next == 0 {
            // Wrap from u64::MAX to 1 (skip 0).  On CAS failure another thread
            // already advanced past MAX; just retry.
            let _ =
                NEXT_JOB_ID.compare_exchange_weak(current, 1, Ordering::Relaxed, Ordering::Relaxed);
            continue;
        }
        if NEXT_JOB_ID
            .compare_exchange_weak(current, next, Ordering::Relaxed, Ordering::Relaxed)
            .is_ok()
        {
            return current;
        }
    }
}

pub fn next_task_id() -> u64 {
    loop {
        let current = NEXT_TASK_ID.load(Ordering::Relaxed);
        let next = current.wrapping_add(1);
        if next == 0 {
            let _ = NEXT_TASK_ID.compare_exchange_weak(
                current,
                1,
                Ordering::Relaxed,
                Ordering::Relaxed,
            );
            continue;
        }
        if NEXT_TASK_ID
            .compare_exchange_weak(current, next, Ordering::Relaxed, Ordering::Relaxed)
            .is_ok()
        {
            return current;
        }
    }
}

pub fn next_request_id() -> u64 {
    loop {
        let current = NEXT_REQUEST_ID.load(Ordering::Relaxed);
        let next = current.wrapping_add(1);
        if next == 0 {
            let _ = NEXT_REQUEST_ID.compare_exchange_weak(
                current,
                1,
                Ordering::Relaxed,
                Ordering::Relaxed,
            );
            continue;
        }
        if NEXT_REQUEST_ID
            .compare_exchange_weak(current, next, Ordering::Relaxed, Ordering::Relaxed)
            .is_ok()
        {
            return current;
        }
    }
}

/// Generate a new unique invocation ID — a UUID v4 rendered as 32 lowercase
/// hex digits, matching the `INVOCATION_ID` format systemd exposes (both in
/// the environment of spawned processes and in the control-port protocol).
pub fn generate_invocation_id() -> String {
    Uuid::new_v4().simple().to_string()
}

// --------------------------------------------------------------------------
// Tests
// --------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use systema_sysf::ir::{DependencySet, MountConfig, UnitType};

    fn mount_ir(id: &str, where_: &str) -> UnitIR {
        UnitIR {
            id: id.to_string(),
            unit_type: Some(UnitType::Mount),
            description: None,
            source_format: Some("dynamic".to_string()),
            source_path: None,
            slice: None,
            dependencies: None,
            service: None,
            mount: Some(MountConfig {
                what: "tmpfs".to_string(),
                where_: where_.to_string(),
                type_: "tmpfs".to_string(),
                options: "rw,nosuid".to_string(),
                timeout_sec: 0,
            }),
            automount: None,
            timer: None,
            socket: None,
            conditions: None,
            asserts: None,
            wanted_by: None,
            required_by: None,
            aliases: Vec::new(),
            resource_control: None,
        }
    }

    fn stage(state: &mut AllocatorState, uid: u32, irs: Vec<UnitIR>) {
        let units: HashMap<String, UnitIR> =
            irs.into_iter().map(|ir| (ir.id.clone(), ir)).collect();
        state
            .init_staging_area(uid, "test", units)
            .expect("staging area created");
    }

    #[test]
    fn commit_creates_units_not_in_cache() {
        let mut state = AllocatorState::new();
        stage(
            &mut state,
            7,
            vec![
                mount_ir("tmp.mount", "/tmp"),
                mount_ir("boot.mount", "/boot"),
            ],
        );

        let count = state.commit_staging(7, "test").unwrap();
        assert_eq!(count, 2);
        let tmp = state.units.get("tmp.mount").unwrap();
        assert_eq!(tmp.kind, UnitKind::Mount);
        assert_eq!(tmp.mount.as_ref().unwrap().where_, "/tmp");
    }

    #[test]
    fn merge_committed_units_notify_the_unit_loaded_channel() {
        // Every unit that enters the allocator through the merge funnel
        // (finder commits and unit.define) must reach the unit-loaded
        // channel so control-plane consumers (bridge flavors) get a
        // `unit.new`; a unit that only gets updated does not re-notify.
        let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<String>();
        let mut state = AllocatorState::new();
        state.unit_loaded_tx = Some(tx);
        let ir = mount_ir("tmp.mount", "/tmp");
        let units: HashMap<String, UnitIR> = HashMap::from([(ir.id.clone(), ir)]);

        let (created, updated) = state.merge_units(&units).unwrap();
        assert_eq!((created, updated), (1, 0));
        assert_eq!(rx.blocking_recv().as_deref(), Some("tmp.mount"));

        // Re-commit an update: no new unit → no duplicate notification.
        let (created, updated) = state.merge_units(&units).unwrap();
        assert_eq!((created, updated), (0, 1));
        assert!(rx.try_recv().is_err(), "updates must not re-notify");
    }

    #[test]
    fn root_slice_always_loaded_and_active() {
        let state = AllocatorState::new();
        let unit = state
            .units
            .get(ROOT_SLICE_NAME)
            .expect("root slice is synthesized");
        assert_eq!(unit.kind, UnitKind::Slice);
        assert_eq!(unit.unit.description, "Root Slice");
        let cached = state
            .unit_states
            .get(ROOT_SLICE_NAME)
            .expect("root slice runtime state");
        assert_eq!(cached.active_state, "active");
        assert_eq!(cached.sub_state, "active");
        assert!(cached.active_enter_timestamp > 0);
        assert_eq!(
            state.desired.get(ROOT_SLICE_NAME),
            Some(&DesiredState::Active)
        );
    }

    #[test]
    fn root_slice_survives_commits() {
        let mut state = AllocatorState::new();
        stage(&mut state, 7, vec![mount_ir("tmp.mount", "/tmp")]);
        state.commit_staging(7, "test").unwrap();
        assert!(state.units.contains_key(ROOT_SLICE_NAME));
        assert_eq!(
            state.unit_states.get(ROOT_SLICE_NAME).unwrap().active_state,
            "active"
        );
    }

    #[test]
    fn commit_merges_only_provided_fields_into_existing_unit() {
        let mut state = AllocatorState::new();
        let mut existing = UnitFile::new("tmp.mount");
        existing.unit.description = "Temporary Directory /tmp".to_string();
        existing.unit.documentation = vec!["man:tmp(5)".to_string()];
        existing.mount = Some(crate::unit::types::MountSection {
            what: "tmpfs".to_string(),
            where_: "/tmp".to_string(),
            timeout_sec: 30,
            ..Default::default()
        });
        state.units.insert("tmp.mount".to_string(), existing);
        stage(&mut state, 7, vec![mount_ir("tmp.mount", "/mnt/tmp")]);

        state.commit_staging(7, "test").unwrap();

        let merged = state.units.get("tmp.mount").unwrap();
        // Description and documentation are not part of the commit → untouched.
        assert_eq!(merged.unit.description, "Temporary Directory /tmp");
        assert_eq!(merged.unit.documentation, vec!["man:tmp(5)".to_string()]);
        // The mount section was provided → overwritten.
        let mnt = merged.mount.as_ref().unwrap();
        assert_eq!(mnt.where_, "/mnt/tmp");
        assert_eq!(mnt.what, "tmpfs");
        assert_eq!(mnt.options, "rw,nosuid");
    }

    #[test]
    fn commit_new_unit_missing_unit_type_is_an_error() {
        let mut state = AllocatorState::new();
        let mut ir = mount_ir("mystery.mount", "/x");
        ir.unit_type = None;
        stage(&mut state, 7, vec![ir]);

        let err = state.commit_staging(7, "test").unwrap_err();
        assert!(err.contains("mystery.mount"), "unexpected error: {err}");
        assert!(err.contains("unit_type"), "unexpected error: {err}");
        assert!(!state.units.contains_key("mystery.mount"));
        // Atomicity: the staging area survives a failed commit.
        assert!(state.get_staging_area(7, "test").is_some());
    }

    #[test]
    fn commit_update_without_unit_type_is_allowed_for_existing_unit() {
        let mut state = AllocatorState::new();
        let mut existing = UnitFile::new("tmp.mount");
        existing.unit.description = "Temporary Directory /tmp".to_string();
        state.units.insert("tmp.mount".to_string(), existing);

        let mut ir = mount_ir("tmp.mount", "/tmp");
        ir.unit_type = None;
        stage(&mut state, 7, vec![ir]);

        state.commit_staging(7, "test").unwrap();
        // Existing unit is patched without needing unit_type.
        assert_eq!(
            state
                .units
                .get("tmp.mount")
                .unwrap()
                .mount
                .as_ref()
                .unwrap()
                .where_,
            "/tmp"
        );
    }

    #[test]
    fn commit_builds_alias_table_and_rewrites_dependency_refs() {
        let mut state = AllocatorState::new();
        // lightdm.service declares display-manager.service as an alias.
        let mut lightdm = UnitFile::new("lightdm.service");
        lightdm
            .install
            .alias
            .push("display-manager.service".to_string());
        state.units.insert("lightdm.service".to_string(), lightdm);
        // graphical.target wants the alias — it must be rewritten.
        let mut graphical = UnitFile::new("graphical.target");
        graphical
            .unit
            .wants
            .insert("display-manager.service".to_string());
        state
            .units
            .insert("graphical.target".to_string(), graphical);

        // Commit any unit to trigger the alias-table rebuild.
        stage(&mut state, 7, vec![mount_ir("tmp.mount", "/tmp")]);
        state.commit_staging(7, "test").unwrap();

        assert_eq!(
            state.resolve_unit_name("display-manager.service"),
            "lightdm.service"
        );
        assert_eq!(
            state.resolve_unit_name("lightdm.service"),
            "lightdm.service"
        );
        let wants = &state.units.get("graphical.target").unwrap().unit.wants;
        assert!(wants.contains("lightdm.service"));
        assert!(!wants.contains("display-manager.service"));
        // Reference counting only ever sees the canonical unit.
        assert!(state
            .get_refs("lightdm.service")
            .iter()
            .any(|s| s == "graphical.target"));
        assert!(!state.ref_counts.contains_key("display-manager.service"));
    }

    #[test]
    fn real_unit_name_wins_over_declared_alias() {
        let mut state = AllocatorState::new();
        let mut lightdm = UnitFile::new("lightdm.service");
        lightdm
            .install
            .alias
            .push("display-manager.service".to_string());
        state.units.insert("lightdm.service".to_string(), lightdm);
        // A real display-manager.service unit exists too: it must not be
        // hijacked by the alias mapping.
        state.units.insert(
            "display-manager.service".to_string(),
            UnitFile::new("display-manager.service"),
        );

        stage(&mut state, 7, vec![mount_ir("tmp.mount", "/tmp")]);
        state.commit_staging(7, "test").unwrap();

        assert_eq!(
            state.resolve_unit_name("display-manager.service"),
            "display-manager.service"
        );
        assert!(state.units.contains_key("display-manager.service"));
    }

    /// Build a `UnitIR` for a target unit with the given wants set, exactly
    /// as the systemd finder emits it (e.g. `graphical.target` with
    /// `wants=["display-manager.service"]`).
    fn target_ir(id: &str, wants: &[&str]) -> UnitIR {
        let mut deps = DependencySet::default();
        deps.wants = wants.iter().map(|s| s.to_string()).collect();
        UnitIR {
            id: id.to_string(),
            unit_type: Some(UnitType::Target),
            description: None,
            source_format: Some("systemd".to_string()),
            source_path: None,
            slice: None,
            dependencies: Some(deps),
            service: None,
            mount: None,
            automount: None,
            timer: None,
            socket: None,
            conditions: None,
            asserts: None,
            wanted_by: None,
            required_by: None,
            aliases: Vec::new(),
            resource_control: None,
        }
    }

    #[test]
    fn finder_ir_target_wants_alias_rewritten_on_commit() {
        // Reproduces the VM rootfs layout through the full finder→commit
        // seam: `graphical.target` wants `display-manager.service`; the
        // finder folds the `display-manager.service -> lightdm.service`
        // symlink into an alias on `lightdm.service` instead of emitting a
        // phantom unit.  After `merge_units`, `rebuild_alias_map` must
        // rewrite the target's wants to the canonical `lightdm.service` so
        // the scheduler pulls it in.  This is the invariant whose breach
        // would make lightdm never start in the VM.
        let mut state = AllocatorState::new();

        let lightdm = UnitIR {
            id: "lightdm.service".to_string(),
            unit_type: Some(UnitType::Service),
            description: None,
            source_format: Some("systemd".to_string()),
            source_path: None,
            slice: None,
            dependencies: None,
            service: Some(Default::default()),
            mount: None,
            automount: None,
            timer: None,
            socket: None,
            conditions: None,
            asserts: None,
            wanted_by: None,
            required_by: None,
            aliases: vec!["display-manager.service".to_string()],
            resource_control: None,
        };
        // `[Install] Alias=display-manager.service` in lightdm.service plus
        // the `/etc/systemd/system/display-manager.service` symlink both feed
        // the same alias; the finder dedupes.
        assert_eq!(lightdm.aliases, vec!["display-manager.service"]);

        let units: HashMap<String, UnitIR> = vec![
            target_ir("graphical.target", &["display-manager.service"]),
            target_ir("multi-user.target", &["systemd-logind.service"]),
            target_ir("default.target", &[]),
            lightdm.clone(),
            target_ir("systemd-logind.service", &[]),
        ]
        .into_iter()
        .map(|ir| (ir.id.clone(), ir))
        .collect();

        state.merge_units(&units).unwrap();

        // The alias is registered, and the target's wants are canonical.
        assert_eq!(
            state.resolve_unit_name("display-manager.service"),
            "lightdm.service"
        );
        let wants = &state.units.get("graphical.target").unwrap().unit.wants;
        assert_eq!(*wants, HashSet::from(["lightdm.service".to_string()]));
        assert!(!wants.contains("display-manager.service"));

        // The reverse: `default.target` resolves to itself.
        assert_eq!(state.resolve_unit_name("default.target"), "default.target");

        // lightdm unit records the alias from the symlink + [Install].
        let lightdm_unit = state.units.get("lightdm.service").unwrap();
        assert!(lightdm_unit
            .install
            .alias
            .contains(&"display-manager.service".to_string()));
    }

    #[test]
    fn commit_failure_applies_no_partial_mutation() {
        let mut state = AllocatorState::new();
        // An existing unit that a failed commit must not touch.
        let mut existing = UnitFile::new("tmp.mount");
        existing.unit.description = "Temporary Directory /tmp".to_string();
        state.units.insert("tmp.mount".to_string(), existing);

        // A patch for the existing unit plus a new unit missing unit_type.
        let units: HashMap<String, UnitIR> = vec![
            mount_ir("tmp.mount", "/mnt/tmp"),
            mount_ir("mystery.mount", "/x"),
        ]
        .into_iter()
        .map(|mut ir| {
            if ir.id == "mystery.mount" {
                ir.unit_type = None;
            }
            (ir.id.clone(), ir)
        })
        .collect();
        state.init_staging_area(7, "test", units).unwrap();

        let err = state.commit_staging(7, "test").unwrap_err();
        assert!(err.contains("unit_type"), "unexpected error: {err}");
        // The existing unit was not patched.
        assert_eq!(
            state.units.get("tmp.mount").unwrap().unit.description,
            "Temporary Directory /tmp"
        );
        assert!(state.units.get("tmp.mount").unwrap().mount.is_none());
        // The staging area survives for a retry.
        assert!(state.get_staging_area(7, "test").is_some());
    }

    #[test]
    fn staging_name_validation() {
        assert!(is_valid_staging_name("systema-sysd/discovery"));
        assert!(is_valid_staging_name("systema-sysm/discovery"));
        assert!(is_valid_staging_name("systema-sysf/discovery"));
        assert!(is_valid_staging_name("foo_bar\\baz-qux"));
        assert!(is_valid_staging_name("A"));
        assert!(is_valid_staging_name(&"a".repeat(64)));

        assert!(!is_valid_staging_name(""));
        assert!(!is_valid_staging_name(&"a".repeat(65)));
        assert!(!is_valid_staging_name("has space"));
        assert!(!is_valid_staging_name("has.dots"));
        assert!(!is_valid_staging_name("has-数字"));
        assert!(!is_valid_staging_name("12345"));
    }

    #[test]
    fn init_staging_area_rejects_invalid_name() {
        let mut state = AllocatorState::new();
        let err = state
            .init_staging_area(9, "system-m mount discovery", HashMap::new())
            .unwrap_err();
        assert!(
            err.contains("invalid staging area name"),
            "unexpected error: {err}"
        );
        assert!(!state
            .staging_areas
            .contains_key(&(9, "system-m mount discovery".to_string())));
    }

    #[test]
    fn multiple_staging_areas_per_uid_coexist() {
        let mut state = AllocatorState::new();
        state
            .init_staging_area(7, "systema-sysd/discovery", HashMap::new())
            .unwrap();
        state
            .init_staging_area(7, "systema-sysm/discovery", HashMap::new())
            .unwrap();
        assert_eq!(state.get_staging_areas_by_uid(7).len(), 2);
        assert_eq!(state.get_staging_areas_by_uid(7).len(), 2);
    }

    #[test]
    fn reinit_same_name_reuses_area_git_style() {
        let mut state = AllocatorState::new();
        let mut first = HashMap::new();
        first.insert("a.service".to_string(), mount_ir("a.service", "/a"));
        state
            .init_staging_area(7, "systema-sysd/discovery", first)
            .unwrap();

        // Re-registering under the same name must not error: units with a
        // matching name are overwritten, new ones are added (union).
        let mut second = HashMap::new();
        second.insert("a.service".to_string(), mount_ir("a.service", "/a-new"));
        second.insert("b.service".to_string(), mount_ir("b.service", "/b"));
        let count = state
            .init_staging_area(7, "systema-sysd/discovery", second)
            .unwrap();
        assert_eq!(count, 2);

        let area = state.get_staging_area(7, "systema-sysd/discovery").unwrap();
        assert_eq!(area.units.len(), 2);
        let a = &area.units["a.service"];
        assert_eq!(a.mount.as_ref().unwrap().where_, "/a-new");
        assert!(area.units.contains_key("b.service"));
    }

    #[test]
    fn staging_areas_isolated_by_uid() {
        let mut state = AllocatorState::new();
        state
            .init_staging_area(7, "systema-sysd/discovery", HashMap::new())
            .unwrap();
        state
            .init_staging_area(8, "systema-sysd/discovery", HashMap::new())
            .unwrap();

        assert!(state
            .get_staging_area(7, "systema-sysd/discovery")
            .is_some());
        assert!(state
            .get_staging_area(8, "systema-sysd/discovery")
            .is_some());
        assert_eq!(
            state
                .get_staging_areas_by_name("systema-sysd/discovery")
                .len(),
            2
        );

        // Committing a staging area that was never created is an idempotent
        // no-op (a consumed area must not be reported as a refused commit
        // when concurrent finder cycles share a fixed staging name).
        assert_eq!(state.commit_staging(7, "systema-sysm/discovery").unwrap(), 0);
        assert_eq!(
            state.commit_staging(7, "systema-sysd/discovery").unwrap(),
            0
        );
        assert!(state
            .get_staging_area(8, "systema-sysd/discovery")
            .is_some());
    }

    #[test]
    fn concurrent_cycles_shared_area_commit_is_idempotent() {
        let mut state = AllocatorState::new();
        // Reproduces the systema-sysr race: its reconnect registration task
        // and its per-session `user.sessions` tasks drive register → commit
        // cycles over the same fixed staging name ("systema-sysr/slices").
        // B registers before A's commit lands, so A's commit publishes the
        // whole shared area (both units) and consumes it.
        state
            .init_staging_area(
                0,
                "systema-sysr/slices",
                HashMap::from([("user.slice".to_string(), mount_ir("user.slice", "/tmp"))]),
            )
            .unwrap();
        state
            .init_staging_area(
                0,
                "systema-sysr/slices",
                HashMap::from([(
                    "user-1000.slice".to_string(),
                    mount_ir("user-1000.slice", "/tmp2"),
                )]),
            )
            .unwrap();

        // A's commit publishes the whole area and removes it.
        assert_eq!(state.commit_staging(0, "systema-sysr/slices").unwrap(), 2);
        assert!(state.units.contains_key("user.slice"));
        assert!(state.units.contains_key("user-1000.slice"));
        assert!(state.get_staging_area(0, "systema-sysr/slices").is_none());

        // B's commit finds the area already consumed: an idempotent no-op,
        // not a refused commit (the "no staging area" regression).
        assert_eq!(state.commit_staging(0, "systema-sysr/slices").unwrap(), 0);
        assert!(state.units.contains_key("user.slice"));
        assert!(state.units.contains_key("user-1000.slice"));
        assert!(state.get_staging_area(0, "systema-sysr/slices").is_none());
    }

    #[test]
    fn session_scope_login_sends_count() {
        let mut sessions = HashMap::new();
        // First session of user 1000: count goes 0 → 1.
        assert_eq!(
            track_session(&mut sessions, "session-1.scope", "user-1000.slice", true),
            Some((1000, 1))
        );
        // A second session of the same user: 1 → 2.
        assert_eq!(
            track_session(&mut sessions, "session-2.scope", "user-1000.slice", true),
            Some((1000, 2))
        );
        // Re-reported active (e.g. resource re-apply): no change.
        assert_eq!(
            track_session(&mut sessions, "session-1.scope", "user-1000.slice", true),
            None
        );
    }

    #[test]
    fn session_scope_logout_releases_count() {
        let mut sessions = HashMap::new();
        track_session(&mut sessions, "session-1.scope", "user-1000.slice", true);
        track_session(&mut sessions, "session-2.scope", "user-1000.slice", true);

        assert_eq!(
            track_session(&mut sessions, "session-1.scope", "user-1000.slice", false),
            Some((1000, 1))
        );
        assert_eq!(
            track_session(&mut sessions, "session-2.scope", "user-1000.slice", false),
            Some((1000, 0))
        );
        assert!(!sessions.contains_key(&1000));
    }

    #[test]
    fn session_tracking_ignores_non_user_units() {
        let mut sessions = HashMap::new();
        // Non-scope unit.
        assert_eq!(
            track_session(&mut sessions, "user@1000.service", "user-1000.slice", true),
            None
        );
        // Scope not living under a user slice.
        assert_eq!(
            track_session(&mut sessions, "session-1.scope", "system.slice", true),
            None
        );
        // Scope under a malformed user slice name.
        assert_eq!(
            track_session(&mut sessions, "session-1.scope", "user-abc.slice", true),
            None
        );
        assert!(sessions.is_empty());
    }

    #[test]
    fn users_tracked_independently() {
        let mut sessions = HashMap::new();
        track_session(&mut sessions, "session-1.scope", "user-1000.slice", true);
        track_session(&mut sessions, "session-1.scope", "user-2000.slice", true);

        // User 1000 logs out; user 2000 is untouched.
        assert_eq!(
            track_session(&mut sessions, "session-1.scope", "user-1000.slice", false),
            Some((1000, 0))
        );
        assert_eq!(sessions.get(&2000).map(|s| s.len()), Some(1));
    }
}
