[package]
name = "systema-sysk"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "systema-sysk"
path = "src/main.rs"

[dependencies]
sysa = { path = "../../libsysa" }

tokio.workspace = true
tokio-util.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
futures.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
prost.workspace = true
libc = "0.2"
