[package]
name = "systema-stagingctl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "systema-stagingctl"
path = "src/main.rs"

[dependencies]
sysa = { path = "../../libsysa" }
sysa-pager = { path = "../../sysa-pager" }

anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
regex.workspace = true
colored.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
