[package]
name = "systema-sysw-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sysa = { path = "../../../libsysa" }

tokio.workspace = true
tokio-util = { workspace = true }
anyhow.workspace = true
prost.workspace = true
bytes.workspace = true
tracing.workspace = true
futures.workspace = true